export const farmProducts = [
  {
    name: "Milk",
    materials: "1 cow feed",
    level: 3,
    sell_price: 7,
    xp: 3,
    time: 1200,
    dealer: 12,
    help: 5,
  },
  {
    name: "Egg",
    materials: "1 chicken feed",
    level: 5,
    sell_price: 10,
    xp: 4,
    time: 3600,
    dealer: 12,
    help: 5,
  },
  {
    name: "Wool",
    materials: "1 sheep feed",
    level: 10,
    sell_price: 15,
    xp: 6,
    time: 14400,
    dealer: 12,
    help: 5,
  },
  {
    name: "Honeycomb",
    materials: "1 bee feed",
    level: 35,
    sell_price: 22,
    xp: 9,
    time: 21600,
    dealer: 12,
    help: 4,
  },
  {
    name: "Bacon",
    materials: "1 pig feed",
    level: 42,
    sell_price: 32,
    xp: 14,
    time: 25200,
    dealer: 12,
    help: 4,
  },
  {
    name: "Down Feather",
    materials: "1 bread,1 bagel, or1 banana bread",
    level: 48,
    sell_price: 12,
    xp: 5,
    time: "1h30m,1h, or30m",
    dealer: 12,
    help: 5,
  },
  {
    name: "Colorful Feather",
    materials: "1 bagel, or1 banana bread",
    level: 48,
    sell_price: 31,
    xp: 13,
    time: "1h,or 30m",
    dealer: 5,
    help: 3,
  },
  {
    name: "Seaweed",
    materials: "1 eggs,1 bacon, or1 fish",
    level: 58,
    sell_price: 43,
    xp: 18,
    time: "4h30m,4h, or3h",
    dealer: 12,
    help: 5,
  },
  {
    name: "Scallop",
    materials: "1 egg,1 bacon, or1 fish",
    level: 58,
    sell_price: 54,
    xp: 23,
    time: "4h30m,4h, or3h",
    dealer: 12,
    help: 4,
  },
  {
    name: "Pearls",
    materials: "1 bacon, or1 fish",
    level: 58,
    sell_price: 64,
    xp: 27,
    time: "4h, or3h",
    dealer: 12,
    help: 3,
  },
  {
    name: "Mushroom",
    materials: "1 Substrate",
    level: 63,
    sell_price: 69,
    xp: 30,
    time: 18000,
    dealer: 12,
    help: 5,
  },
];

export const feeds = [
  {
    name: "Cow Feed",
    materials: [
      {
        id: "lOCBkEDWyF7XEYPvrucQ",
        quantity: 2,
      },
      {
        id: "GtSUfRIsCUyg1U66q0OW",
        quantity: 1,
      },
    ],
    level: 3,
    sell_price: 1,
    xp: 1 / 3,
    time: 100,
    dealer: 4,
    help: 2,
  },
  {
    name: "Chicken Feed",
    materials: [
      {
        id: "lOCBkEDWyF7XEYPvrucQ",
        quantity: 2,
      },
      {
        id: "lpz6Nga2oEmtPUjxOn3t",
        quantity: 1,
      },
    ],
    level: 5,
    sell_price: 4 / 3,
    xp: 2 / 3,
    time: 200,
    dealer: 4,
    help: 2,
  },
  {
    name: "Sheep Feed",
    materials: [
      {
        id: "GtSUfRIsCUyg1U66q0OW",
        quantity: 2,
      },
      {
        id: "lpz6Nga2oEmtPUjxOn3t",
        quantity: 2,
      },
    ],
    level: 10,
    sell_price: 5 / 3,
    xp: 2 / 3,
    time: 400,
    dealer: 4,
    help: 2,
  },
  {
    name: "Bee Feed",
    materials: [
      {
        id: "lOCBkEDWyF7XEYPvrucQ",
        quantity: 3,
      },
      {
        id: "kQGQlNDHv55X64fIeRZQ",
        quantity: 1,
      },
    ],
    level: 35,
    sell_price: 7 / 3,
    xp: 1,
    time: 600,
    dealer: 4,
    help: 2,
  },
  {
    name: "Pig Feed",
    materials: [
      {
        id: "lOCBkEDWyF7XEYPvrucQ",
        quantity: 2,
      },
      {
        id: "lpz6Nga2oEmtPUjxOn3t",
        quantity: 2,
      },
      {
        id: "GtSUfRIsCUyg1U66q0OW",
        quantity: 1,
      },
    ],
    level: 42,
    sell_price: 10 / 3,
    xp: 4 / 3,
    time: 800,
    dealer: 4,
    help: 2,
  },
  {
    name: "Substrate",
    materials: [
      {
        id: "1oipzlweHN9GzNyDTdUK",
        quantity: 1,
      },
      {
        id: "lFXeZhBt1VvaJz7Z5gnb",
        quantity: 1,
      },
      {
        id: "GtSUfRIsCUyg1U66q0OW",
        quantity: 2,
      },
    ],
    level: 63,
    sell_price: 23 / 3,
    xp: 5 / 3,
    time: 1000,
    dealer: 4,
    help: 2,
  },
];
