import { PropsWithChildren, Fragment } from "react";
import Head from "next/head";
import { Navbar } from "components";

interface Props {
  title?: string;
}

function Layout({
  children,
  title = "Township - Management",
}: PropsWithChildren<Props>) {
  return (
    <Fragment>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>{children}</main>
    </Fragment>
  );
}

export default Layout;
