import axios from "axios";
import Head from "next/head";
import { GetStaticProps } from "next";
import { Good } from "../types";

interface Props {
  goods: Good[];
}

function Home({ goods }: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {goods.length === 0 && <p>No items</p>}
        <ul>
          {goods.map((good) => (
            <li key={good.id}>
              <p>{good.name}</p>
              <p>Cost: {good.cost}</p>
              <p>Level: {good.level}</p>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  try {
    const { data: goods } = await axios.get("http://localhost:3000/api/goods");
    return {
      props: {
        goods,
      },
    };
  } catch (error) {
    return {
      props: {
        goods: [],
      },
    };
  }
};

export default Home;
